global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['0.0.0.0:9090']
  - job_name: pushgateway
    static_configs:
      - targets: ['0.0.0.0:9091']
